In [118]:
import pandas as pd
import os
import math

In [9]:
os.getcwd()

'C:\\Users\\kam224\\OneDrive - Imperial College London\\Documents\\NumericsProject2\\New folder'

In [80]:
df1 = pd.read_csv("../results/results_diff_10e-5.csv", index_col = "time", names = ["time", "diff 10e-5"], header = 0)
df2 = pd.read_csv("../results/results_diff_10e-6.csv", index_col = "time", names = ["time", "diff 10e-6"],  header = 0)
df3 = pd.read_csv("../results/results_diff_10e-7.csv", index_col = "time", names = ["time", "diff 10e-7"],  header = 0)

In [92]:
df = df1.join([df2, df3])

In [100]:
df.index = (df.index - 0.1)/3600

In [110]:
df.to_csv("full_data.csv", sep = "&", lineterminator = "\\\\ \n \\hbar \n")

In [120]:
trunc = lambda x: math.trunc(1000 * x) / 1000;

df.map(trunc)

      diff 10e-5  diff 10e-6  diff 10e-7
time
1.0        0.000       0.000       0.000
2.0        0.000       0.000       0.000
3.0        0.000       0.000       0.000
4.0       -0.004      -0.004      -0.004
5.0        0.001       0.001       0.001
6.0       -0.434      -0.434      -0.434
7.0       -0.004      -0.004      -0.004
8.0       -0.002      -0.002      -0.002
9.0        0.010       0.010       0.010
10.0       0.011       0.011       0.011
11.0       0.013       0.013       0.013
12.0       0.008       0.008       0.008
13.0       0.000       0.000       0.000
14.0       0.000       0.000       0.000
15.0       0.000       0.000       0.000
16.0      -0.002      -0.002      -0.002

In [122]:
df

        diff 10e-5    diff 10e-6    diff 10e-7
time
1.0   2.440393e-07  2.440393e-07  2.440393e-07
2.0   2.684125e-06  2.684126e-06  2.684126e-06
3.0  -2.932826e-04 -2.932827e-04 -2.932827e-04
4.0  -4.021176e-03 -4.021178e-03 -4.021178e-03
5.0   1.788435e-03  1.788436e-03  1.788436e-03
6.0  -4.348072e-01 -4.347670e-01 -4.347630e-01
7.0  -4.239198e-03 -4.239194e-03 -4.239194e-03
8.0  -2.105426e-03 -2.105425e-03 -2.105425e-03
9.0   1.014541e-02  1.014542e-02  1.014542e-02
10.0  1.197798e-02  1.197800e-02  1.197800e-02
11.0  1.334238e-02  1.334224e-02  1.334223e-02
12.0  8.365051e-03  8.365037e-03  8.365035e-03
13.0  1.983897e-04  1.983900e-04  1.983900e-04
14.0 -7.383826e-05 -7.383831e-05 -7.383831e-05
15.0  2.094315e-04  2.094316e-04  2.094316e-04
16.0 -2.510664e-03 -2.510671e-03 -2.510672e-03